name: Deploy to charactergeneratorweb

on:
  push:
    paths:
      - '人物生成器/Web ver/index.html'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Copy index.html to target repository
      run: |
        # 克隆目标仓库
        git clone https://github.com/your-username/charactergeneratorweb.git charactergeneratorweb
        # 检查目标仓库中是否有 index.html 文件
        if [ ! -f 'charactergeneratorweb/index.html' ]; then
          echo "index.html not found in target repository, creating an empty one."
          touch 'charactergeneratorweb/index.html'
        fi
        # 将源仓库中的 index.html 文件复制到目标仓库
        cp '人物生成器/Web ver/index.html' 'charactergeneratorweb/index.html'
        cd charactergeneratorweb

    - name: Commit and push the changes
      run: |
        git add index.html
        git commit -m "Update index.html"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
